# Generated by Django 4.1.4 on 2023-01-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_toy_alter_feeding_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
